#!usr/bin/env bash

# setup

declare -A file_type

mkdir -p assets
touch assets/cool{1..3}.md assets/secret{1..5}.pdf assets/cool_script

mkdir -p assets/cool_dir{1..4}

chmod +x assets/cool_script

#check all files in directory
#store what type of file it is
#regular, executable, directory
#
for f in assets/*; do
    filename="${#*/}"
    echo "$filename"

if [[ -d "$f" ]]; then
    file_type ["$filename"]="directory"
elif [[ -x "$f" ]]; then
    file_type ["$filename"]="executable"

else [[ - "$f" ]]; then
    file_type ["$filename"]="regular"

fi

done

