#!/usr/bin/env bash
#
fruits=(apple pear banana kiwi)
echo "@fruits"
echo "${fruits[0]}"

echo "${fruits[2]}"

#Index from end
echo "${fruits[-1]}"
#selects all
echo "${fruits[@]}"

#slicing
echo "${fruits[@]:1:2}"



