#!/usr/bin/env bash

#output redirection
echo '# input and output' > README.md
# >overwrite content (clobering)
# >> appends aka adds
echo 'notes blah blah' > README.md

echo  >> README.md

ls >> README.md

echo
echo "current working directory is " >> README.md	
 pwd >> README.md
