#!/usr/bin/env bash
# range based for loops

for i in {1..6}; do
    echo "cool_$i"
done  

#list based for loop

for animal in kangaroo rabbit dog cat; do
    echo "animal $i: $animal"
    ((i=1)) 

done


#C-style loop




